### ISSUE TITLE
Availability via maven repo

### ISSUE THREAD

**Issue by JamzTheMan** [hendraanggrian/packr-gradle-plugin#1]
Hi, looks like this is an active plugin so going to give it a try!  Will you be release 0.3 via maven repos? I can only seem to pull down v0.1?

**Comment by hendraanggrian** [comment]
It is available in [jcenter](https://bintray.com/hendraanggrian/packr/packr-gradle-plugin), but be sure to add maven url `https://oss.sonatype.org/content/repositories/snapshots` since I'm using snapshot build of [the origional packr](https://github.com/libgdx/packr).

How can you only download version 0.1? Can you elaborate?

**Comment by hendraanggrian** [comment]
Update: it turns out this plugin isn't yet on jcenter. Add `https://dl.bintray.com/hendraanggrian/packr` to buildscript repositories after this is resolved.

**Comment by dbof10** [comment]
```Could not find com.hendraanggrian.packr:packr-gradle-plugin:0.9.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/hendraanggrian/packr/packr-gradle-plugin/0.9/packr-gradle-plugin-0.9.pom
       - https://dl.google.com/dl/android/maven2/com/hendraanggrian/packr/packr-gradle-plugin/0.9/packr-gradle-plugin-0.9.jar
       - https://jcenter.bintray.com/com/hendraanggrian/packr/packr-gradle-plugin/0.9/packr-gradle-plugin-0.9.pom
       - https://jcenter.bintray.com/com/hendraanggrian/packr/packr-gradle-plugin/0.9/packr-gradle-plugin-0.9.jar
       - https://oss.sonatype.org/content/repositories/snapshots/com/hendraanggrian/packr/packr-gradle-plugin/0.9/packr-gradle-plugin-0.9.pom
       - https://oss.sonatype.org/content/repositories/snapshots/com/hendraanggrian/packr/packr-gradle-plugin/0.9/packr-gradle-plugin-0.9.jar```

**Comment by dbof10** [comment]
then I have another error

```
Companion
Open File
```

**Comment by hendraanggrian** [comment]
@dbof10 may I see your full Gradle scripts?

**Comment by hendraanggrian** [comment]
in `buildscript.repositories`, add classpath `https://dl.bintray.com/hendraanggrian/packr`. I have no idea why jcenter won't host the latest version of this plugin, in the meantime please manually add the classpath.

**Comment by hendraanggrian** [comment]
In your `buildscript`, you need to add repository maven url `https://dl.bintray.com/hendraanggrian/packr`, then add classpath `com.hendraanggrian.packr:packr-gradle-plugin:$version`.

See README for more.

**Comment by dbof10** [comment]
then I have another error

```Companion
Open File```

**Comment by GDownes** [comment]
I'm also having this issue.
Does this plugin work?

**Comment by GDownes** [comment]
Hi Hendra,

Thanks for your help,

The linked example doesn't include any repositories  to showcase resolving the plugin. 

I'm unable to resolve the plugin. Following the readme instructions and guidance listed on this issue has lead me to the same issue posted

**Comment by hendraanggrian** [comment]
I have re-released this plugin into new maven url: `com.hendraanggrian:packr-gradle-plugin:$version`. It should fix this issue for now.
