### ISSUE TITLE
outputDir getting errors!

### ISSUE THREAD

**Issue by khintk** [hendraanggrian/packr-gradle-plugin#4]
Hi, 

I have been trying to specify the output Dir however, I keep running into this error of 
Could not find method outputDir() for arguments [/Users/xxx/Downloads] on object of type com.hendraanggrian.packr.PackrExtension. Here is the code that I specify 
````
        executable 'Night Shift'
        classpath 'desktop/build/libs/desktop-1.0.jar'
        mainClass 'com.nightshift.game.desktop.DesktopLauncher'
        outputDir '/Users/xxx/Downloads'
````

**Comment by hendraanggrian** [comment]
`outputDir` accepts `File` input, not String. So try: 

```gradle
outputDir new File('/Users/xxx/Downloads')
```

I will switch it to String on the next version.

**Comment by hendraanggrian** [comment]
Version 0.7 has been released with string input on `classpath`, `resources`, and `outputDirectory`. Note that any path input will be relative to project directory, so `/Users/xxx/Downloads` won't actually deploy in your default download folder. Instead, it will deploy in `path/to/your/project//Users/xxx/Downloads`.

**Comment by khintk** [comment]
Thanks for a new version! Using the version, the outputDir works. However, in the directory that I specified, it didn't spit out the game version in Mac and Window. I am wondering if I am missing something. 
```
packr {
        executable 'NightShift'
        classpath 'desktop/build/libs/desktop-1.0.jar'
        mainClass 'com.nightshift.game.desktop.DesktopLauncher'
        outputDir new File('/Users/xxx/Documents/Software_In_Production/NightShift')

        macOS {
            it.name 'NightShiftMac.app'
            it.jdk '/Users/xxx/Downloads/jdk.zip'
            it.bundleId 'com.NightShift.app'
        }
        windows64 {
            it.name 'NightShiftWindow.app'
            it.jdk '/Users/xxx/Downloads/jre-windows.zip'
        }

        verbose true
        openOnDone true
    }
```

**Comment by hendraanggrian** [comment]
First, I have updated version 0.7 with absolute path support. But then you should also change your classpath:

```gradle
classpath "$projectDir/desktop/build/libs/desktop-1.0.jar"
// or classpath "$projectDir/desktop/build/libs"
outputDir '/Users/xxx/Downloads'
```

Second about the executables not being generated, I can only help if you are using the latest version. Make sure you're using version 0.7 and you can sync Gradle successfully, I am here if you need any assistance.

**Comment by khintk** [comment]
I tried it with 0.5, and it works but I am getting the wrong idk perhaps because I have been getting this error Couldn't find JRE in JDK when running the executable. I am wondering about the idk package.
